### ISSUE TITLE
运行中出现的bug

### ISSUE THREAD

**Issue by JackyWang0001** [Jianfu-She/Face-Alignment#1]
你好，我最近下载编译了你的程序，并用你的程序来截取眼睛样本。但我在运行的程序的过程中碰到了一个问题，即程序在处理图片的过程中会出现OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in
 cv::Mat::Mat, file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\cor
e\src\matrix.cpp, line 323。不知这个问题可否有解决方案？

**Comment by Jianfu-She** [comment]
应该是对于眼睛的定位出现了问题，错误的定位点导致切割图片时出现了“越界”。

**Comment by Jianfu-She** [comment]
应该是对于眼睛的定位出现了问题，错误的定位点导致切割图片时出现了“越界”。
